In [1]:
# importing numpy
import numpy as np
a = np.arange(1,31).reshape(6,5)
a
slice = a[2:,1:3]
slice

array([[12, 13],
       [17, 18],
       [22, 23],
       [27, 28]])

In [2]:
import numpy as np
arr1 = np.array([[1,2,3],[2,3,4],[2,3,4]])
arr2 =np.array([[1,2,4],[2,3,9],[2,8,4]])
arr1 @ arr2

array([[11, 32, 34],
       [16, 45, 51],
       [16, 45, 51]])

In [3]:
import numpy as np


In [4]:
a = np.array([1,2,3])
a


array([1, 2, 3])

In [5]:
import numpy as np
data = np.array([
    [18,85,78],
    [19,92,88],
    [17,76,95],
    [18,65,70],
    [20,90,85]])


In [6]:
#get the shape of the matrix
data.shape

(5, 3)

In [7]:
np.mean(data[:,0])

np.float64(18.4)

In [8]:
c = np.array(data[:,1])
c

array([85, 92, 76, 65, 90])

In [9]:

s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1], 
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [10]:
f = np.sum(s,axis=0)
for i in f:
    if( i != 45):
        print("not valid")
        break
else:
    print("valid")

valid


In [11]:
h = np.sum(s,axis =1)
h

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [12]:
m = s[ :3, :3]
m

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [13]:
print(m.sum())

45


In [14]:
for i in range (0,9,3):
    for j in range(0,9,3):
        n = (s[i:i+3,j:j+3])
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [15]:
import numpy as np
data = np.array([
    [18,85,78],
    [19,92,88],
    [17,76,95],
    [18,65,70],
    [20,90,85]])

In [16]:
n = data[:,1]
n

array([85, 92, 76, 65, 90])

In [17]:
n = np.mean(n)

In [18]:
n

np.float64(81.6)

In [19]:
s = np.mean(data[:,2])
s

np.float64(83.2)

In [20]:
np.mean(data[:,1 :],axis =0)


array([81.6, 83.2])

In [21]:
# q = data[data[:,1]>=80]
# q
# q = data[data[:,1]>=80] and data[data[:,2]>=80]
# q
q = data[(data[:,1]>=80) & (data[:,2]>=80)]
q

array([[19, 92, 88],
       [20, 90, 85]])

In [23]:
data[:,2][data[:,2]<75] =0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])